# Generated by Django 3.0.6 on 2020-06-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmwareTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('queue_time', models.DateTimeField()),
                ('state', models.CharField(max_length=20, null=True)),
                ('entity_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
