# Generated by Django 3.0.6 on 2020-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vmwaretasks_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmwaretasks',
            name='key',
        ),
        migrations.AddField(
            model_name='vmwaretasks',
            name='chain_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
