# Generated by Django 3.0.6 on 2020-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200602_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmwaretasks',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
