# Generated by Django 3.0.6 on 2020-06-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vmwaretasks_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VmwareTasks',
        ),
    ]
