# Generated by Django 3.0.6 on 2020-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SudoTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('user', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('ticket', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[('PENDING', 0), ('ADDED', 1), ('EXPIRED', 2), ('REMOVED', 3)], default=0)),
            ],
        ),
    ]
