# Generated by Django 3.0.6 on 2020-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20200822_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudotasks',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
