# Generated by Django 3.0.6 on 2020-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20200822_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudotasks',
            name='status',
            field=models.SmallIntegerField(choices=[('PENDING', 0), ('ADDED', 1), ('EXPIRED', 2), ('REMOVED', 3), ('FAILED', 4)], default=0),
        ),
    ]
