# Generated by Django 3.0.6 on 2020-08-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20200823_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudotasks',
            name='status',
            field=models.SmallIntegerField(choices=[('PENDING', 0), ('ADDED', 1), ('EXPIRED', 2), ('REMOVED', 3), ('FAILED', 4), ('RUNNING', 5), ('REMOVING', 6)], default=0),
        ),
    ]
