# Generated by Django 3.0.6 on 2020-11-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_sudotasks_effective_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Groups')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Users')),
            ],
        ),
        migrations.CreateModel(
            name='SudoConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='ALL', max_length=20)),
                ('run_as', models.CharField(default='ALL', max_length=255)),
                ('commands', models.TextField()),
                ('command_alias', models.CharField(max_length=255, null=True)),
                ('args', models.CharField(max_length=255, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='HostsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Groups')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Hosts')),
            ],
        ),
    ]
