# Generated by Django 3.0.6 on 2020-11-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_groups_hosts_hostsgroups_sudoconfigs_users_usersgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='type',
            field=models.SmallIntegerField(choices=[('USER_GROUP', 0), ('HOST_GROUP', 1)], default=0),
        ),
    ]
