# Generated by Django 3.0.6 on 2021-02-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_groups_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_list', models.TextField()),
                ('id_code', models.CharField(default=django.db.models.deletion.SET_NULL, max_length=255, null=True, unique=True)),
                ('operator', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[('PENDING', 0), ('RUNNING', 1), ('AWX_DONE', 2), ('DONE', 3)], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='awxjobs',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='awxjobs',
            name='task_id',
        ),
        migrations.AddField(
            model_name='awxjobs',
            name='host_id_list',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField()),
                ('task_type', models.SmallIntegerField(choices=[('SUDO', 0), ('COLLECTOR', 1)])),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.AWXJobs')),
            ],
        ),
        migrations.CreateModel(
            name='SudoScanResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=255)),
                ('user_type', models.SmallIntegerField(choices=[('USER', 0), ('LOCAL_GROUP', 1), ('NET_GROUP', 2)])),
                ('src_host', models.CharField(max_length=100)),
                ('run_as', models.CharField(max_length=255)),
                ('commands', models.TextField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.CollectorTasks')),
            ],
        ),
    ]
