# Generated by Django 3.0.6 on 2021-02-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_auto_20210202_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectortasks',
            name='id_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
