# Generated by Django 3.0.6 on 2021-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_cvelist_vulsscanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvelist',
            name='details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
