# Generated by Django 3.0.6 on 2021-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_cvelist_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulsScanTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=255, null=True, unique=True, verbose_name='hashed code for filename')),
                ('status', models.SmallIntegerField(choices=[('PENDING', 0), ('RUNNING', 1), ('AWX_DONE', 2), ('DONE', 3)], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='collectortasks',
            name='id_code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='hashed id for filename'),
        ),
        migrations.AlterField(
            model_name='taskjobs',
            name='task_type',
            field=models.SmallIntegerField(choices=[('SUDO', 0), ('COLLECTOR', 1), ('VULSCAN', 2)]),
        ),
    ]
