# Generated by Django 3.0.6 on 2021-04-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_auto_20210331_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudotasks',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='sudotasks',
            name='user',
        ),
        migrations.AddField(
            model_name='sudotasks',
            name='hosts',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sudotasks',
            name='users',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
