# Generated by Django 3.0.6 on 2020-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=100)),
                ('datacenter', models.CharField(max_length=50)),
                ('cluster', models.CharField(max_length=100)),
                ('datastore', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('mask', models.CharField(max_length=30)),
                ('gateway', models.GenericIPAddressField()),
                ('cpu', models.SmallIntegerField()),
                ('memory', models.SmallIntegerField()),
                ('vlan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.BigIntegerField(unique=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('queue_time', models.DateTimeField()),
                ('state', models.CharField(max_length=20, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('entity_name', models.CharField(max_length=255, null=True)),
                ('type', models.SmallIntegerField(choices=[('snapshot', 0), ('depoly', 1)])),
                ('msg', models.TextField(null=True)),
            ],
        ),
    ]
