# Generated by Django 3.0.6 on 2020-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0002_auto_20200602_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylists',
            name='vcenter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
