# Generated by Django 3.0.6 on 2020-06-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0003_deploylists_vcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylists',
            name='state',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='deploylists',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
