# Generated by Django 3.0.6 on 2020-06-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0006_auto_20200603_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploylists',
            old_name='vm_name',
            new_name='servername',
        ),
    ]
