# Generated by Django 3.0.6 on 2020-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0009_deploylists_chain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylists',
            name='template',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
