# Generated by Django 3.0.6 on 2020-06-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0010_deploylists_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylists',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
