# Generated by Django 3.0.6 on 2020-06-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0011_deploylists_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploylists',
            options={'permissions': [('can_read_vmware_deploy_list', 'Permission to read vmware deploy list'), ('can_change_vmware_deploy_list', 'Permission to modify vmware deploy listt'), ('can_add_vmware_deploy_list', 'Permission to add vmware deploy list'), ('can_delete_vmware_deploy_list', 'Permission to delete vmware deploy listt')]},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'permissions': [('can_read_vmware_tasks', 'Permission to read vmware tasks'), ('can_change_vmware_tasks', 'Permission to modify vmware tasks'), ('can_add_vmware_tasks', 'Permission to add vmware tasks'), ('can_delete_vmware_tasks', 'Permission to delete vmware tasks')]},
        ),
    ]
