# Generated by Django 3.0.6 on 2021-03-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0012_auto_20200610_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=255)),
                ('vm_uuid', models.UUIDField()),
                ('vm_path', models.TextField()),
                ('vm_vc', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('keep_days', models.SmallIntegerField(default=5)),
                ('snap_name', models.CharField(max_length=255)),
                ('snap_desc', models.TextField()),
                ('snap_mem', models.BooleanField(default=False)),
                ('snap_qui', models.BooleanField(default=False)),
                ('snap_remove_child', models.BooleanField(default=False)),
                ('snap_sol', models.BooleanField(default=False)),
                ('state', models.SmallIntegerField(choices=[('pending', 0), ('done', 1), ('expired', 2), ('removed', 3), ('fail', 4), ('retry', 5)], default=0)),
            ],
            options={
                'permissions': [('can_read_vmware_snapshots', 'Permission to read vmware snapshots'), ('can_change_vmware_snapshots', 'Permission to modify vmware snapshots'), ('can_add_vmware_snapshots', 'Permission to add vmware snapshots'), ('can_delete_vmware_snapshots', 'Permission to delete vmware snapshots')],
            },
        ),
    ]
