# Generated by Django 3.0.6 on 2021-03-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0013_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshots',
            name='vm_uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
