# Generated by Django 3.0.6 on 2021-03-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0014_auto_20210309_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshots',
            name='operator',
            field=models.CharField(default='joshua', max_length=255),
            preserve_default=False,
        ),
    ]
